#!/usr/bin/env bash

DOTFILES=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

rm -rf $HOME/.gitconfig
ln -s $DOTFILES/git/.gitconfig $HOME/.gitconfig

rm -rf $HOME/.gitignore
ln -s $DOTFILES/git/.gitignore $HOME/.gitignore



